### PR TITLE
a more robust way of handling diverging blocks

### LINKED ISSUE #15: Duplicate brands with dead-code drop calls
Hi!

The following program compiles fine with current Rust (and runs fine, and then loops), even though it should not, right? If you remove the `loop {}` line, it will fail with a borrow-check error, as expected:

```rust
use generativity::{Id, make_guard};

fn test<'id>(a: Id<'id>, b: Id<'id>) {
    print!("{:?} and {:?}\n", a, b);
    assert_eq!(a, b);
}

fn foo() {
    make_guard!(g_a);
    make_guard!(g_b);

    let a: Id = g_a.into();
    let b: Id = g_b.into();

    test(a, b);

    loop {}
}

fn main() {
    foo();
}
```

I think this boils down to [NLL-borrowck ignoring dead-code](https://github.com/rust-lang/rust/issues/91377#issuecomment-993875185).

Not sure how to fix this.
David

### PR DESCRIPTION
**Pull request by RustyYato**
Fixes #15

Based on my comment here: https://github.com/CAD97/generativity/issues/15#issuecomment-3423285988

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -165,7 +165,7 @@ impl<'id> LifetimeBrand<'id> {
 ///
 /// Multiple `make_guard` lifetimes will always fail to unify:
 ///
-/// ```rust,compile_fail,E0597
+/// ```rust,compile_fail,E0716
```
Comment (RustyYato) [inline src/lib.rs:168]: The error code changed, but it's still the same error kind

File: tests/ui/diverging_fn.stderr [hunk 2]
```diff
@@ -1,75 +1,14 @@
-error: unreachable expression
```
Comment (RustyYato) [inline tests/ui/diverging_fn.stderr:1]: instead of a forbid warning, we now have a hard error 🎉

**Comment by RustyYato** [comment]
Just realized this needs to be made robust, instead of using `Some` and `None` from prelude...
Will do later today

**Comment by RustyYato** [comment]
ping @CAD97 :)

**Comment by CAD97** [comment]
Sorry this took so long to merge! I've been busy being hired and that's taken a lot of my energy this past bit. Doing required publish things now.

**Comment by CAD97** [comment]
The fix is now (finally) published! 🎉
https://github.com/CAD97/generativity/releases/tag/v1.2.1
https://crates.io/crates/generativity/1.2.1

**Comment by RustyYato** [comment]
No worries, thanks for publishing my fix!
